### ISSUE TITLE
[Question] example of FFI for function pointers?

### ISSUE THREAD

**Issue by ghost** [pure11/pure11#2]
Are there any examples for function pointer casting from `any`? My use case is making `map` for an FFI data container where I want to apply the function pointer in C++. 

In particular, while I could create getters and setters, and do `map` on the Purescript side, in particular I want to iterate on the C++ for system implementation reasons.

I tried what I thought was the obvious thing, with `cast<any(*)(const any &)>` for a simple function, but that didn't compile.

Suggestions?

**Comment by andyarvanitis** [comment]
There currently isn't a cast operator defined for it, mainly because `any` could hold either a true function pointer or a lambda closure. I should think about adding one, though, at least maybe to a `std::function`. But for your case, you can simply use the function call operator on your variable (`any` handles it properly). In other words:
```C++
auto myFunc(const any& f) -> any {
  const auto result = f(100);
  return result;
}
```

This is done pretty often in the standard library FFI implementations. I should add more about it in the documentation too.

Let me know if that helps.

**Comment by ghost** [comment]
OK, great, thanks!
